version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    # environment:
    #   - DJANGO_DB_HOST=db
    #   - DJANGO_DB_PORT=5432
    #   - DJANGO_DB_NAME=mydb
    #   - DJANGO_DB_USER=myuser
    #   - DJANGO_DB_PASSWORD=mypassword
  pgdb:
    image: postgres
    container_name: pgdb #postgres database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres