version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/app
    # depends_on:
    #   - db
    # environment:
    #   - DJANGO_DB_HOST=db
    #   - DJANGO_DB_PORT=5432
    #   - DJANGO_DB_NAME=mydb
    #   - DJANGO_DB_USER=myuser
    #   - DJANGO_DB_PASSWORD=mypassword
  # db:
  #   image: postgres:12
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword